export const en = {
  'nav.workspace':'Workspace','nav.dashboard':'Dashboard','nav.applications':'Applications','nav.followUps':'Follow-ups','nav.signedInAs':'Signed in as','nav.signOut':'Sign out','nav.signingOut':'Signing out…','nav.signOutError':'Unable to sign out.',
  'prefs.appearance':'Appearance','prefs.light':'Light','prefs.dark':'Dark','prefs.themeLabel':'Use dark theme','prefs.language':'Language','general.notifications':'Notifications',
  'auth.eyebrow':'Your career workspace','auth.hero':'Keep every opportunity moving forward.','auth.heroText':'Organize applications, stay on top of follow-ups, and see your progress clearly—all in one focused workspace.','auth.tracker':'Job Application Tracker','auth.signIn':'Sign in','auth.create':'Create an account','auth.access':'Access your application workspace.','auth.start':'Create an account to start tracking opportunities.','auth.email':'Email','auth.password':'Password','auth.required':'Email and password are required.','auth.accountCreated':'Account created. Check your email to confirm your account before signing in.','auth.failed':'Authentication could not be completed.','auth.googleFailed':'Google authentication could not be started.','auth.wait':'Please wait…','auth.googleConnecting':'Connecting to Google…','auth.google':'Continue with Google','auth.noAccount':"Don't have an account?",'auth.hasAccount':'Already have an account?','auth.signUp':'Sign up','auth.or':'or',
  'dashboard.overview':'Overview','dashboard.title':'Dashboard','dashboard.description':'A clear view of your applications and latest activity.','dashboard.view':'View applications','dashboard.total':'Total applications','dashboard.active':'Active applications','dashboard.interviews':'Interviews','dashboard.offers':'Offers','dashboard.rejected':'Rejected applications','dashboard.distribution':'Status distribution','dashboard.distributionHelp':'See how your applications are moving through the pipeline.','dashboard.totalSuffix':'total','dashboard.recent':'Recently updated','dashboard.recentHelp':'Your latest application activity.','dashboard.loading':'Loading dashboard','dashboard.loadingHelp':'Preparing your application overview…','dashboard.empty':'No applications yet','dashboard.emptyHelp':'Add your first opportunity to start building your application overview.','dashboard.add':'Add application','dashboard.summary':'Application summary',
  'applications.eyebrow':'Job Application Tracker','applications.title':'Applications','applications.description':'Keep track of every opportunity and see where each application stands.','applications.add':'Add application','applications.filter':'Filter applications','applications.filtersActive':'Filters active','applications.search':'Search','applications.searchPlaceholder':'Company, position, or technology','applications.status':'Status','applications.workMode':'Work mode','applications.source':'Source','applications.allStatuses':'All statuses','applications.allWorkModes':'All work modes','applications.allSources':'All sources','applications.clear':'Clear filters','applications.countOne':'{count} application','applications.countMany':'{count} applications','applications.list':'List','applications.board':'Board','applications.view':'Application view','applications.loading':'Loading applications…','applications.empty':'No applications yet','applications.emptyHelp':'Add your first opportunity to begin tracking your job search.','applications.none':'No applications found','applications.noneHelp':'Try changing or clearing your filters.','applications.retry':'Try again','applications.region':'Job applications','applications.boardRegion':'Applications board','applications.deleted':'Application deleted.','applications.deleteFailed':'Unable to delete the application. Please try again.','applications.statusMoved':'Application moved to {status}.','applications.statusFailed':'Unable to change the application status. Please try again.','applications.updated':'Application updated.','applications.created':'Application created.','applications.updateFailed':'Unable to update the application. Please try again.','applications.createFailed':'Unable to create the application. Please try again.',
  'form.add':'Add application','form.edit':'Edit application','form.addHelp':'Record a new opportunity in your application tracker.','form.editHelp':'Update the details for this job application.','form.opportunity':'Opportunity','form.opportunityHelp':'Core details about the role and company.','form.tracking':'Tracking','form.trackingHelp':'Where this application currently stands.','form.work':'Work details','form.workHelp':'Optional context about the opportunity.','form.additional':'Additional information','form.additionalHelp':'Useful context for later conversations.','form.company':'Company','form.position':'Position','form.status':'Status','form.source':'Source','form.workMode':'Work mode','form.employmentType':'Employment type','form.location':'Location','form.jobUrl':'Job URL','form.nextAction':'Next action date','form.technologies':'Technologies','form.technologiesHint':'Separate technologies with commas.','form.notes':'Notes','form.selectStatus':'Select status','form.selectSource':'Select source','form.notSpecified':'Not specified','form.companyRequired':'Company is required.','form.positionRequired':'Position is required.','form.statusRequired':'Status is required.','form.sourceRequired':'Source is required.','form.cancel':'Cancel','form.saving':'Saving…','form.saveChanges':'Save changes','form.save':'Save application',
  'card.workMode':'Work mode','card.source':'Source','card.applied':'Applied {date}','card.nextAction':'Next action {date}','card.viewJob':'View job','card.edit':'Edit','card.delete':'Delete','card.salary':'Salary','card.technologies':'Technologies','card.deleteTitle':'Delete {position} at {company}?','card.deleteDescription':'This application will be permanently removed. This action cannot be undone.','card.deleteConfirm':'Delete application',
  'board.noApplications':'No applications','board.countOne':'{count} application','board.countMany':'{count} applications',
  'follow.eyebrow':'Next actions','follow.title':'Follow-ups','follow.description':'Review overdue actions and plan your next conversations.','follow.overdue':'Overdue','follow.today':'Today','follow.upcoming':'Upcoming','follow.overdueHelp':'Actions that have passed their scheduled date.','follow.todayHelp':'Actions scheduled for today.','follow.upcomingHelp':'Actions planned for the days ahead.','follow.empty':'No follow-ups scheduled','follow.emptyHelp':'Add a next action date to an active application to see it here.','follow.groupEmpty':'No {group} follow-ups.','follow.loading':'Loading follow-ups…','follow.reschedule':'Reschedule','follow.update':'Update','follow.updating':'Updating…','follow.complete':'Mark complete','follow.completing':'Completing…','follow.completed':'Follow-up completed.','follow.completeFailed':'Unable to complete the follow-up. Please try again.','follow.rescheduled':'Follow-up rescheduled.','follow.rescheduleFailed':'Unable to reschedule the follow-up. Please try again.',
  'status.saved':'Saved','status.applied':'Applied','status.test':'Test','status.interview':'Interview','status.offer':'Offer','status.rejected':'Rejected','status.withdrawn':'Withdrawn','work.remote':'Remote','work.hybrid':'Hybrid','work.onsite':'On-site','employment.clt':'CLT','employment.pj':'PJ','employment.internship':'Internship','employment.trainee':'Trainee','employment.contract':'Contract','employment.other':'Other','source.linkedin':'LinkedIn','source.gupy':'Gupy','source.company':'Company website','source.referral':'Referral','source.other':'Other',
  'general.dismiss':'Dismiss','general.dismissNotification':'Dismiss {variant} notification','general.cancel':'Cancel','general.confirm':'Confirm','general.deleting':'Deleting…','general.loadingSession':'Loading your session…','notFound.eyebrow':'404','notFound.title':'Page not found','notFound.description':'The page you are looking for does not exist.','notFound.back':'Back to dashboard','meta.title':'ApplyFlow — Job Application Tracker','meta.description':'Track job applications, interviews, follow-ups and offers in one organized workspace.'
} as const

export type TranslationKey = keyof typeof en
export type TranslationDictionary = Record<TranslationKey, string>

export const ptBR: TranslationDictionary = {
  ...en,
  'general.notifications':'Notificações',
  'nav.workspace':'Espaço de trabalho','nav.dashboard':'Visão geral','nav.applications':'Candidaturas','nav.followUps':'Acompanhamentos','nav.signedInAs':'Conectado como','nav.signOut':'Sair','nav.signingOut':'Saindo…','nav.signOutError':'Não foi possível sair.',
  'prefs.appearance':'Aparência','prefs.light':'Claro','prefs.dark':'Escuro','prefs.themeLabel':'Usar tema escuro','prefs.language':'Idioma',
  'auth.eyebrow':'Seu espaço de carreira','auth.hero':'Mantenha cada oportunidade em movimento.','auth.heroText':'Organize candidaturas, acompanhe próximos passos e veja seu progresso com clareza em um só lugar.','auth.tracker':'Rastreador de candidaturas','auth.signIn':'Entrar','auth.create':'Criar uma conta','auth.access':'Acesse seu espaço de candidaturas.','auth.start':'Crie uma conta para começar a acompanhar oportunidades.','auth.email':'E-mail','auth.password':'Senha','auth.required':'E-mail e senha são obrigatórios.','auth.accountCreated':'Conta criada. Verifique seu e-mail para confirmar a conta antes de entrar.','auth.failed':'Não foi possível concluir a autenticação.','auth.googleFailed':'Não foi possível iniciar a autenticação com o Google.','auth.wait':'Aguarde…','auth.googleConnecting':'Conectando ao Google…','auth.google':'Continuar com Google','auth.noAccount':'Ainda não tem uma conta?','auth.hasAccount':'Já tem uma conta?','auth.signUp':'Criar conta','auth.or':'ou',
  'dashboard.overview':'Resumo','dashboard.title':'Visão geral','dashboard.description':'Uma visão clara das suas candidaturas e atividades recentes.','dashboard.view':'Ver candidaturas','dashboard.total':'Total de candidaturas','dashboard.active':'Candidaturas ativas','dashboard.interviews':'Entrevistas','dashboard.offers':'Propostas','dashboard.rejected':'Candidaturas rejeitadas','dashboard.distribution':'Distribuição por status','dashboard.distributionHelp':'Veja como suas candidaturas avançam pelo processo.','dashboard.totalSuffix':'no total','dashboard.recent':'Atualizadas recentemente','dashboard.recentHelp':'Suas atividades mais recentes.','dashboard.loading':'Carregando visão geral','dashboard.loadingHelp':'Preparando o resumo das suas candidaturas…','dashboard.empty':'Nenhuma candidatura ainda','dashboard.emptyHelp':'Adicione sua primeira oportunidade para começar.','dashboard.add':'Nova candidatura','dashboard.summary':'Resumo das candidaturas',
  'applications.eyebrow':'Rastreador de candidaturas','applications.title':'Candidaturas','applications.description':'Acompanhe cada oportunidade e saiba em que etapa ela está.','applications.add':'Nova candidatura','applications.filter':'Filtrar candidaturas','applications.filtersActive':'Filtros ativos','applications.search':'Buscar','applications.searchPlaceholder':'Empresa, cargo ou tecnologia','applications.status':'Status','applications.workMode':'Modelo de trabalho','applications.source':'Origem','applications.allStatuses':'Todos os status','applications.allWorkModes':'Todos os modelos','applications.allSources':'Todas as origens','applications.clear':'Limpar filtros','applications.countOne':'{count} candidatura','applications.countMany':'{count} candidaturas','applications.list':'Lista','applications.board':'Quadro','applications.view':'Visualização das candidaturas','applications.loading':'Carregando candidaturas…','applications.empty':'Nenhuma candidatura ainda','applications.emptyHelp':'Adicione sua primeira oportunidade para começar sua busca.','applications.none':'Nenhuma candidatura encontrada','applications.noneHelp':'Altere ou limpe os filtros.','applications.retry':'Tentar novamente','applications.region':'Candidaturas','applications.boardRegion':'Quadro de candidaturas','applications.deleted':'Candidatura excluída.','applications.deleteFailed':'Não foi possível excluir a candidatura. Tente novamente.','applications.statusMoved':'Candidatura movida para {status}.','applications.statusFailed':'Não foi possível alterar o status. Tente novamente.','applications.updated':'Candidatura atualizada.','applications.created':'Candidatura criada.','applications.updateFailed':'Não foi possível atualizar a candidatura. Tente novamente.','applications.createFailed':'Não foi possível criar a candidatura. Tente novamente.',
  'form.add':'Nova candidatura','form.edit':'Editar candidatura','form.addHelp':'Registre uma nova oportunidade.','form.editHelp':'Atualize os dados desta candidatura.','form.opportunity':'Oportunidade','form.opportunityHelp':'Dados principais da vaga e da empresa.','form.tracking':'Acompanhamento','form.trackingHelp':'A etapa atual desta candidatura.','form.work':'Detalhes do trabalho','form.workHelp':'Contexto opcional sobre a oportunidade.','form.additional':'Informações adicionais','form.additionalHelp':'Contexto útil para conversas futuras.','form.company':'Empresa','form.position':'Cargo','form.status':'Status','form.source':'Origem','form.workMode':'Modelo de trabalho','form.employmentType':'Tipo de contratação','form.location':'Localização','form.jobUrl':'URL da vaga','form.nextAction':'Data da próxima ação','form.technologies':'Tecnologias','form.technologiesHint':'Separe as tecnologias por vírgulas.','form.notes':'Observações','form.selectStatus':'Selecione o status','form.selectSource':'Selecione a origem','form.notSpecified':'Não informado','form.companyRequired':'Empresa é obrigatória.','form.positionRequired':'Cargo é obrigatório.','form.statusRequired':'Status é obrigatório.','form.sourceRequired':'Origem é obrigatória.','form.cancel':'Cancelar','form.saving':'Salvando…','form.saveChanges':'Salvar alterações','form.save':'Salvar candidatura',
  'card.workMode':'Modelo de trabalho','card.source':'Origem','card.applied':'Candidatura em {date}','card.nextAction':'Próxima ação em {date}','card.viewJob':'Ver vaga','card.edit':'Editar','card.delete':'Excluir','card.salary':'Salário','card.technologies':'Tecnologias','card.deleteTitle':'Excluir {position} na {company}?','card.deleteDescription':'Esta candidatura será removida permanentemente. Esta ação não pode ser desfeita.','card.deleteConfirm':'Excluir candidatura',
  'board.noApplications':'Nenhuma candidatura','board.countOne':'{count} candidatura','board.countMany':'{count} candidaturas',
  'follow.eyebrow':'Próximas ações','follow.title':'Acompanhamentos','follow.description':'Revise ações atrasadas e planeje seus próximos contatos.','follow.overdue':'Atrasados','follow.today':'Hoje','follow.upcoming':'Próximos','follow.overdueHelp':'Ações que passaram da data agendada.','follow.todayHelp':'Ações agendadas para hoje.','follow.upcomingHelp':'Ações planejadas para os próximos dias.','follow.empty':'Nenhum acompanhamento agendado','follow.emptyHelp':'Adicione uma data de próxima ação a uma candidatura ativa.','follow.groupEmpty':'Nenhum acompanhamento em {group}.','follow.loading':'Carregando acompanhamentos…','follow.reschedule':'Reagendar','follow.update':'Atualizar','follow.updating':'Atualizando…','follow.complete':'Concluir','follow.completing':'Concluindo…','follow.completed':'Acompanhamento concluído.','follow.completeFailed':'Não foi possível concluir. Tente novamente.','follow.rescheduled':'Acompanhamento reagendado.','follow.rescheduleFailed':'Não foi possível reagendar. Tente novamente.',
  'status.saved':'Salva','status.applied':'Candidatado','status.test':'Teste','status.interview':'Entrevista','status.offer':'Proposta','status.rejected':'Rejeitada','status.withdrawn':'Desistência','work.remote':'Remoto','work.hybrid':'Híbrido','work.onsite':'Presencial','employment.internship':'Estágio','employment.trainee':'Trainee','employment.contract':'Contrato','employment.other':'Outro','source.company':'Site da empresa','source.referral':'Indicação','source.other':'Outro',
  'general.dismiss':'Fechar','general.dismissNotification':'Fechar notificação','general.cancel':'Cancelar','general.confirm':'Confirmar','general.deleting':'Excluindo…','general.loadingSession':'Carregando sua sessão…','notFound.eyebrow':'404','notFound.title':'Página não encontrada','notFound.description':'A página que você procura não existe.','notFound.back':'Voltar para a visão geral','meta.title':'ApplyFlow — Rastreador de Candidaturas','meta.description':'Organize candidaturas, entrevistas, acompanhamentos e propostas em um só lugar.'
}

export const translations = { 'pt-BR': ptBR, en }
